name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  app:
    name: App - Typecheck & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npx tsc -p tsconfig.json --noEmit

      - name: Lint
        run: npm run lint

      - name: Tests (if present)
        run: npm run test --if-present

  functions:
    name: Functions - Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: functions/package-lock.json

      - name: Install dependencies (root)
        run: npm ci

      - name: Install dependencies (functions)
        run: npm --prefix functions ci

      - name: Build functions
        run: npm --prefix functions run build

      - name: Test functions
        run: npm --prefix functions run test

  smoke:
    name: Emulator smoke test (createInvite/acceptInvite)
    runs-on: ubuntu-latest
    needs: [app, functions]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies (root)
        run: npm ci

      - name: Install dependencies (functions)
        run: npm --prefix functions ci

      - name: Build functions
        run: npm --prefix functions run build

      - name: Setup Java (for Firebase emulators)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Run smoke test
        env:
          CI: true
        run: npx firebase emulators:exec --project demo-homecontrol --only functions,firestore,auth 'node scripts/smoke-invites.js'
